### ISSUE TITLE
Documentation: clarify dynamic max_age is ignored with SESAME_MAX_AGE = None (the default)

### ISSUE THREAD

**Issue by silviogutierrez** [aaugustin/django-sesame#106]
I suspected this, as the docs clearly state SESAME_MAX_AGE set to None means we have no timestamps of any kind.

But `authenticate` and `get_user` will still happily accept `max_age=5` but this will be silently ignored.

Not a huge issue, but given `SESAME_MAX_AGE` defaults to None, worth clarifying.

Let me know if this makes sense and I can open a docs PR.

Thanks for all the great work on this library.

**Comment by aaugustin** [comment]
You're supposed to get a [warning](https://github.com/aaugustin/django-sesame/blob/349b172038952f3758b7dde8ab7aee11cbe0bf66/src/sesame/tokens_v2.py#L199-L202) for this. Are you not seeing the warning?
