### ISSUE TITLE
Non existent user ID returned / Security concerns

### ISSUE THREAD

**Issue by patroqueeet** [aaugustin/django-sesame#108]
Hello @aaugustin haven't been talking here for a while :). Was using this beautiful lib heavily.

Now I see the following:

code:
```
def get_user_from_token(token):
    """from
    https://github.com/aaugustin/django-sesame/blob/dba0895508b4febe15a84b24f1e9bbe531eed88b/src/sesame/tokens_v2.
    """
    token = token.encode()

    try:
        data = base64.urlsafe_b64decode(token + b"=" * (-len(token) % 4))
    except Exception:
        logger.debug("Bad token: cannot decode token")
        return

    # Extract user primary key, token age, and signature from token.

    try:
        user_pk, timestamp_and_signature = packers.packer.unpack_pk(data)
    except Exception:
        logger.debug("Bad token: cannot extract primary key")
        return

    try:
        return User.objects.get(pk=user_pk)
    except User.DoesNotExist:
        raise InvalidSesameToken(f"Invalid token w/ non-existent user id {user_pk}")
```

and I receive this token from some random source.

`?sesame=BBF67jajAH1cfd1C8giBVaAlDkUc6hiycY-vxeEcFaLFBw40l1mgKAcFlElHXDzD8EftUdfD-dKZ3deFacG6C96IfZkB2f0V`

and as you will see, when you apply the code above: this will raise 

```
InvalidSesameToken at <SOME URL>
Invalid token w/ non-existent user id 68254446
```

what I'm worried about: it seems to me that someone out there is able to fake the token to basically be able to brute-force try out user IDs and being able to gain unauthorised access.

**Comment by aaugustin** [comment]
Well, you discovered that django-sesame is slightly infringing on the cryptographic doom principle ;-)

The user ID is in plain text in the token. It's just the first 4 or 8 bytes after base64 decoding, depending on the type of your primary keys. Anyone can fake the user ID by changing the token (on purpose or accidentally). Then django-sesame tells you that it received an unkonwn user ID. This can help debug problems.

However, they cannot fake the signature. If they land on a valid user ID, django-sesame will raise an exception saying that the signature is invalid. There are unit tests for this in the code base.

**Comment by aaugustin** [comment]
The test for the scenario you're concerned about is here: https://github.com/aaugustin/django-sesame/blob/349b172038952f3758b7dde8ab7aee11cbe0bf66/tests/test_tokens_v2.py#L447-L448

**Comment by patroqueeet** [comment]
@aaugustin thx for providing this precise answer and the code to see myself. removed the custom method listed above from my code and replaced it with `parse_token` to ensure after the user is determined, that the signature matches.
