### ISSUE TITLE
Limiting logins to only browser that requested link through cookies

### ISSUE THREAD

**Issue by hgezim** [aaugustin/django-sesame#14]
Does it make sense to set a cookie on the client when the user clicks "get link" and then check against the cookie before the authentication succeeds?

**Comment by aaugustin** [comment]
Also, most often, the person who uses the link isn't the same person who generates the link.

**Comment by hgezim** [comment]
I just implemented django-sesame and am using it in production. This would be a nice option to help with security a tad. I noticed that Medium doesn't care either.

**Comment by aaugustin** [comment]
I'm still unsure about what that would mean for django-sesame in practice. If you have a concrete proposal of APIs that django-sesame could implement, let's reopen the discussion.
