### ISSUE TITLE
Last login not updated

### ISSUE THREAD

**Issue by hgezim** [aaugustin/django-sesame#15]
It appears that last login field is not updated at all when magic link is used to auth.

**Comment by aaugustin** [comment]
Django updates the `last_login` field when the `user_logged_in` signal is sent. That signal is sent by the `django.contrib.auth.login()` function which django-sesame calls [here](https://github.com/aaugustin/django-sesame/blob/dc5d8b0a7e69548c1691d0dc0ac4f0547ac03e2b/sesame/middleware.py#L37).

Is `sesame.middleware.AuthenticationMiddleware` after `django.contrib.sessions.middleware.SessionMiddleware` and `django.contrib.auth.middleware.AuthenticationMiddleware` in your `MIDDLEWARE` setting?

**Comment by hgezim** [comment]
Yes, indeed, I do have them in that order:

```py
    'django.contrib.sessions.middleware.SessionMiddleware',
    ...,
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'sesame.middleware.AuthenticationMiddleware',
    ...
```

**Comment by hgezim** [comment]
Never mind! It's not an issue after-all.
