### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [aaugustin/django-sesame#24]
Hi @aaugustin  I am a logo designer. I have reviewed and appreciate your depo. I want to support the open source community by designing logos. I designed a logo for django-sesame. I want to know what you think. Best regards.

![DJ](https://user-images.githubusercontent.com/36298335/57014631-a9c8c480-6c19-11e9-88ed-3f6ff4f80c9c.jpg)

Readme file view;

![dj2](https://user-images.githubusercontent.com/36298335/57014688-d8469f80-6c19-11e9-8b95-977e849db855.png)

**Comment by aaugustin** [comment]
Thanks for the offer! I'd love to add a logo to django-sesame.

It makes sense to use a link symbol plus something about authentication.

(My first idea would be to push the "open sesame" pun. However that doesn't look easy. A sesame seed doesn't have a memorable shape!)

In your proposal, I'm worried that the link symbol isn't sufficiently identifiable. I understood the person shape; I wondered about the weird arms until I read the explanation :-)

Perhaps a "link + key" design would be easier than a "link + user" design? That's quite a different proposal from what you started, so I would understand if you didn't want to explore that.

If you want to push your initial proposal further, perhaps it would work better with that kind of icon? https://thenounproject.com/term/url/1364051/ It could be a better approximation of a person's shoulders. Or perhaps that kind? https://thenounproject.com/term/url/194434/ I'm not finding an horizontal version of this shape, imagine rotating it horizontally.

Thanks again!

**Comment by aaugustin** [comment]
PS - if you'd like to focus on a more popular project, I'm sure that http://websockets.readthedocs.io/ could use a better logo than what I designed ;-)

**Comment by reallinfo** [comment]
hi again @aaugustin  Thanks for the suggestion. I really like the key and url idea. I created a logo by combining these two keywords. What do you think? btw, I'll think of the idea of ​​the logo for websocket. 

![DJ](https://user-images.githubusercontent.com/36298335/57051473-5773bc00-6c8a-11e9-8382-67187288a786.jpg)

**Comment by aaugustin** [comment]
That looks really good!

Did you use the official Django green for the green version? I'm happy to let you choose the color you like best; I'm just suggesting that, if you're close enough to Django green, then better use the exact color:

- RGB: R:9 G:46 B:32
- Web (hex): #092E20
- CMYK: C:90 M:50 Y:80 K:60

Also, could you provide a SVG version?

**Comment by reallinfo** [comment]
I think django color will represent the application better. I applied the official color. Thanks! Ofcourse, I can send a pr for all variations(horizontal, vertical, icon) as svg.

**Comment by aaugustin** [comment]
Thank you very much!

I will also add the logo to the README (as soon as I figure out RST syntax for images).

**Comment by reallinfo** [comment]
haha you're rigt. I tried to update the readme file but could not :D Have a nice day!
