### ISSUE TITLE
Safari detection misses iOS browsers

### ISSUE THREAD

**Issue by pjsier** [aaugustin/django-sesame#27]
The issue with Safari getting logged out by the redirect after clicking the magic link still occurs on iOS browsers including mobile Safari, Chrome, and Firefox. Making the browser check in `is_safari` a bit more flexible fixes it locally, and I can put in a PR for that if it's useful

**Comment by aaugustin** [comment]
Thanks for the report

We need to improve this check:

https://github.com/aaugustin/django-sesame/blob/a5e65cc75947dbce428cdb623ce882775f6ffcb5/sesame/middleware.py#L62-L63

Here are some browsers families that may have ITP:

```
$ grep family uap.yaml | grep -v '#' | sort | uniq | grep '\(Apple\|Safari\|WebKit\)'
    family_replacement: 'Apple Mail'
    family_replacement: 'BlackBerry WebKit'
    family_replacement: 'Mobile Safari UI/WKWebView'
    family_replacement: 'Mobile Safari'
    family_replacement: 'Safari'
    family_replacement: 'WebKit Nightly'
```

You report that it happens on all mobile browsers on iOS (and, I guess, tvOS). This means we also need to test for the OS in addition to the browser family.

I knew that all iOS browsers must use WebKit for rendering; I wasn't sure if that included cookie management; apparently it does.

A PR would be much appreciated :-)

**Comment by aaugustin** [comment]
I pushed a new release to PyPI with your fix to make it easier for you to deploy it.

**Comment by pjsier** [comment]
Great, thanks for the quick review!
