### ISSUE TITLE
SESAME_ONE_TIME failing

### ISSUE THREAD

**Issue by finestructure** [aaugustin/django-sesame#29]
I've set up a test for token re-use with `SESAME_ONE_TIME` set to `True` and I'm running the following test:

```
    def test_reuse(self):
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        token = get_parameters(alice)['url_auth_token']
        assert token
        user = authenticate(url_auth_token=token)
        assert user == alice
        user = authenticate(url_auth_token=token)
        assert user is None  # fails: user still alice
```

The issue appears to be that `user.last_login` remains `None` after `authenticate` is being called and therefore in backends.py:97

```
        if self.one_time:
            value += str(user.last_login)
```

does not lead to a change in `get_revocation_key`.

I wonder: is my assumption wrong that `authenticate` should count as a login in therefore invalidate the token? Or should I be using a different mechanism to use and invalidate the token?

Thanks a lot!

**Comment by finestructure** [comment]
Just to confirm: I've set `SESAME_ONE_TIME` as follows in `settings.py`:

```
SESAME_ONE_TIME = True
```

i.e. at the top level and not in any dictionary or list. That's the correct syntax, isn't it?

**Comment by aaugustin** [comment]
Calling `django.contrib.auth.login(request, user)` invalidates one-time tokens.

Calling `django.contrib.auth.authenticate(url_auth_token=token)` doesn't.

On one hand, given the current documentation, it's quite reasonable to expect that a successful `authenticate` will invalidate a one-time token.

On the other hand, the current behavior is a straightforward consequence of how `django.contrib.auth` works and can be extended.

I think the best way forwards is to keep the current behavior and impove  the documentation.

**Comment by finestructure** [comment]
Thanks for the quick response, @aaugustin 

I tested with `authenticate`, because I thought that's what's used under the hood. I'm not actually calling any methods explicitly. Rather, I was testing using the query string twice in the following test and accompanying implementation:

```
    def test_reuse(self):
        """Test token re-user"""
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        qs = get_query_string(alice)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 200
        assert res.data['id'] == alice.id

        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 403  # <-- fails, getting 200
```

```
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

    @action(detail=False)
    def me(self, request):
        user = get_user(request)
        if user is None:
            raise PermissionDenied
        serializer = self.get_serializer(user)
        return Response(serializer.data)
```

This is the variant without the middleware in between but I'm getting the same results if I let the middleware process the query string and simply use `request.user`.

Should the middleware using and unwrapping the token - hence in my mind "logging the user in" - not invalidate the token?

Or do I need to explicitly call `login` on all endpoints in order to update `last_login`? That seems error prone. If not now, I'm surely going to forget instrumenting one later on. think🤔

**Comment by finestructure** [comment]
PS: I've tried `self.client.session.clear()` in between requests

**Comment by aaugustin** [comment]
The intended use case for `SESAME_ONE_TIME` is password reset links. They should expire when they've been used.

I'm not sure why you're using `SESAME_ONE_TIME` but it looks like something else. If I understood your use case, probably I'd be in a better position to help.

**Comment by aaugustin** [comment]
What do you think about #32?

**Comment by finestructure** [comment]
Thanks a lot for the follow-up, @aaugustin .

I *think* our use case is quite similar to a password reset link. We're sending out links to documents and want to be able to sign the user in with a one-use link.

Maybe the following test that goes through the api layer explains this better:

```
    def test_reuse_2(self):
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        qs = get_query_string(alice)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 200
        assert res.data['id'] == alice.id

        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 403  # FIXME: failing, 200 instead
```

I'm using an api endpoint that's equivalent to `/api/users/{id}` here to get back user info for the authenticated user.

I imagine this is quite similar to what a password reset link should do, isn't it?

I can obviously go into the endpoint implementation and ensure that `last_login` is updated but we're going to have various endpoints handling those links and it's easy to miss one.

Mainly, I wanted to mention that I thought some underlying process that maps the token to the user object ensures the token is invalidated at the same time.

For reference, this is the endpoint:

```
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

    @action(detail=False)
    def me(self, request):
        user = request.user
        if user is None or not user.is_authenticated:
            raise PermissionDenied
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)
```

My understanding is that the sesame middleware populates `request.user` in the above snippet. At that point I was expecting the token to be invalidated (i.e. `last_login` to be set) without having to remember to do so myself.

This may be a totally wrong assumption - this is simply me asking if it's an oversight or intended behaviour :)

**Comment by finestructure** [comment]
As to #32 I think you're saying it is indeed intended behaviour and up to us to ensure we invalidate the tokens by setting `last_login` or calling `login` ourselves in endpoints that handle token :)

**Comment by aaugustin** [comment]
> At that point I was expecting the token to be invalidated (i.e. last_login to be set) without having to remember to do so myself.

Yes, I'm expecting this as well. I don't understand the behavior you're seeing.

Since I don't have access to your setup to debug this, could you confirm if code execution goes through the following lines?

- https://github.com/aaugustin/django-sesame/blob/b3a94352f5d907063af03c8aec44f14a7c09da6f/sesame/middleware.py#L33
- https://github.com/django/django/blob/4b6dfe16226a81fea464ac5f77942f4d6ba266e8/django/contrib/auth/__init__.py#L131
- https://github.com/django/django/blob/master/django/contrib/auth/models.py#L20

**Comment by finestructure** [comment]
I haven't had a chance yet to step through all three places yet but here's what happens in the middle ware for this test:

```
    def test_reuse_2(self):
        """Test token re-user"""
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        qs = get_query_string(alice)

        breakpoint()
        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 200
        assert res.data['id'] == alice.id

        res = self.client.get('/api/users/me/' + qs, follow=True)
        assert res.status_code == 403  # FIXME: failing, 200 instead
```

The first line is line 35 in a larger test file.

Here's a gist with the debug session output: https://gist.github.com/finestructure/8b3e757d528252c59a8047c43cf12a97

**Comment by aaugustin** [comment]
> As to #32 I think you're saying it is indeed intended behaviour and up to us to ensure we invalidate the tokens by setting `last_login` or calling `login` ourselves in endpoints that handle token :)

I wanted to say the exact opposite :-(

The only situation where you need to do so is if you're using the low-level `django.contrib.auth.authenticate()` API. If you don't use django-sesame's helpers, there isn't much I can do to help.

**Comment by aaugustin** [comment]
> I thought some underlying process that maps the token to the user object ensures the token is invalidated at the same time.

That process consists in updating the user's `last_login` date. However, since you don't want to make a database write with every HTTP request, this needs to be done carefully.

In a cookie-based authentication scenario, the sesame token is validated, then the user is logged-in (which updates `last_login`) and then authentication is preserved in cookies.

**Comment by aaugustin** [comment]
I can reproduce the issue with this test:

```python
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.test import TestCase, override_settings
from django.urls import path
from sesame.utils import get_query_string, get_user


def me(request):
    user = get_user(request)
    if user is None:
        raise PermissionDenied
    user_data = vars(user)
    user_data.pop('_state')
    return JsonResponse(user.__dict__)


urlpatterns = [path('api/users/me/', me)]


@override_settings(ROOT_URLCONF=__name__)
class TestIssue29(TestCase):

    def test_reuse_2(self):
        """Test token re-user"""
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        qs = get_query_string(alice)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.json()['id'], alice.id)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        self.assertEqual(res.status_code, 403)
```

It also happens on the branch for #32. I'm going to investigate.

**Comment by aaugustin** [comment]
I wrote this test case to reproduce your scenario. I made it as similar as possible to the code you provided, minus DRF.

```python
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.test import TestCase, override_settings
from django.urls import path
from sesame.utils import get_query_string, get_user

# Necessary override_settings(SESAME_ONE_TIME=True)
from sesame import test_signals


def me(request):
    user = get_user(request)
    if user is None:
        raise PermissionDenied
    user_data = vars(user)
    user_data.pop('_state')
    return JsonResponse(user.__dict__)


urlpatterns = [path('api/users/me/', me)]


@override_settings(ROOT_URLCONF=__name__, SESAME_ONE_TIME=True)
class TestIssue29(TestCase):

    def test_reuse_2(self):
        alice = User.objects.create_user(username='alice@bar.com', password='foobar123')
        qs = get_query_string(alice)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.json()['id'], alice.id)

        res = self.client.get('/api/users/me/' + qs, follow=True)
        self.assertEqual(res.status_code, 403)
```

It fails on master and passes on the branch for #32.

----

So, can we consider that #32 is the way to go, with better documentation (since my initial attempt confused you)?

**Comment by finestructure** [comment]
That looks great, thanks a lot for following up!

**Comment by aaugustin** [comment]
I pushed version 1.7 which includes this fix.

**Comment by finestructure** [comment]
Can confirm that after updating to 1.7 my tests are now all passing. Thanks again for the fix!
