### ISSUE TITLE
Sesame invalidate on password change set to False, no effect.

### ISSUE THREAD

**Issue by ronaldlangeveld** [aaugustin/django-sesame#36]
My use case is to use Sesame as a form of 2FA. Eg user enters username + password then emails the Sesame auth link to login.

Just to clarify, I've set the following in my settings.py, so that users can change their password at in settings. 
`SESAME_INVALIDATE_ON_PASSWORD_CHANGE = False`

However users are still being logged out after changing their password as it redirects to /accounts/login upon refresh.

**Comment by aaugustin** [comment]
`SESAME_INVALIDATE_ON_PASSWORD_CHANGE` controls whether sesame tokens remain valid, not session invalidation by django.contrib.auth.

I think you're looking for https://docs.djangoproject.com/en/2.2/topics/auth/default/#session-invalidation-on-password-change
