### ISSUE TITLE
expired url_auth_token does not raise PermissionDenied

### ISSUE THREAD

**Issue by sdementen** [aaugustin/django-sesame#41]
I have several authentication backend configured in Django.
I use an url_auth_token in a URL to allow Insomnia to import from this URL that needs authentication.
When I call the URL with a token that has expired, the sesame middleware return None, letting other middleware to kick in instead of raising a PermissionDenied.
This is a problem (for me) as the following authentication backends redirect the users to login pages (which Insomnia does not handle properly).
Debugging this is difficult and it would be better to see a 403 (giving the user an hint that the token is not valid.

In utils.py/get_user method, I would adapt the lines 42-44 to 
```
    user = authenticate(request, url_auth_token=url_auth_token)
    if user is None:
        # return None
        from django.core.exceptions import PermissionDenied
        raise PermissionDenied
```

does it make sense ?

**Comment by aaugustin** [comment]
https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#writing-an-authentication-backend says:

> `authenticate()` should check the credentials it gets and return a user object that matches those credentials if the credentials are valid. If they’re not valid, it should return `None`.

Raising an exception isn't part of the API contract.

**Comment by aaugustin** [comment]
One solution would be to detect when the user attempted to authenticate with a token and not to redirect to the login page in that case.

**Comment by sdementen** [comment]
You're right, in https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#handling-authorization-in-custom-backends I read 
"If a backend raises a PermissionDenied exception in has_perm() or has_module_perms(), the authorization will immediately fail and Django won’t check the backends that follow." And so thought about a permissiondenied but it is about authorization, not really authentication.
