### ISSUE TITLE
Token expired or used error state handling

### ISSUE THREAD

**Issue by samloomes** [aaugustin/django-sesame#44]
Thanks so much for your great work on this package, I'm using it on a new project and it's been really seamless so far.

One thing I'm struggling with, is there a recommended way of handling the event in which tokens are either expired or one time tokens have already been used? I'd like to display an error message or redirect users to a view if they were unable to log in. This recent issue seems to touch on the subject: https://github.com/aaugustin/django-sesame/issues/41

Is there a standard Django way of handling failed authentication that has gone through all the authentication middleware or would I need to extend Sesame to handle this case?

Thanks again

**Comment by aaugustin** [comment]
The standard Django way is [login_required](https://docs.djangoproject.com/fr/2.2/topics/auth/default/#the-login-required-decorator) which redirects to a login page.

You can change LOGIN_URL to something other than a login form if you don't have a login form because only django-sesame provides authentication.

**Comment by samloomes** [comment]
Thanks for that Aymeric, that put me on the right track.

I ended up pointing the magic link to redirect view that uses the LoginRequiredMixin. On failure I send the user to the login view with a query string parameter to show an error message, otherwise I redirect to my homepage with a query string parameter to show a "you have been logged in message".

Think that covers it all. Again this is a great package, I can't see anything else out there handling this so nicely.

**Comment by aaugustin** [comment]
Yes, that's a smart way to achieve what you want!

I expect others may have the same need. I'm going to reopen the issue to check if I can find a good way to document it.

**Comment by aaugustin** [comment]
I reviewed this issue today. Mixing `LoginRequiredMixin` and `RedirectView` may yield the best result in your situation, however I don't think that's the most straightforward solution in general. 

So I'm going to stick with the basic example in the "Per-view authentication" paragraph in the README. I'm adding more explanations so it's more likely to help someone with the same question as you.
