### ISSUE TITLE
Register with django-sesame

### ISSUE THREAD

**Issue by migueltorrescosta** [aaugustin/django-sesame#47]
I would like to implement a passwordless model that checks email ownership and registers a user in one go. The idea is to get to the login page. This creates an account for the user if that email is not registered, and sends a magic link for the user to login. Is this something you support? At no moment passwords are created.

I have had a look through the git README.md and existing issues and was not able to find anything related to it. I apologize if I missed it somewhere.

Best,
Miguel

**Comment by migueltorrescosta** [comment]
Managed to get this done :) Django-sesame is awesome

**Comment by aaugustin** [comment]
Glad you figured it out!

For anyone else who stumbles upon this ticket, django-sesame only takes care of generating the login link. It's up to you to build everything else — mostly, a view that determines whether it's a existing or a new user, creates it if needed, and sends an email with the login link.

**Comment by fabge** [comment]
as i can see, the current implementation always expects a user to be passed to `create_token`.

but i would like a new user to be able to put his/her email in the magic link form, get the magic link - but the user should not be created **until the magic link is clicked**.
is this possible currently? i would probably have to write custom functions for that @aaugustin?

**Comment by aaugustin** [comment]
In this scenario, you have to store somehow the relationship between the email and the token that you generated, so you can validate it when the user clicks the link. django-sesame leverages the auth.User model for this purpose. If you have a constraint not to use auth.User, indeed django-sesame won't work for you.

Then you'll have store that relationship elsewhere. At this point, you can simply create a table with three fields:

- email
- token - [token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe) is a good choice for generating it
- created_at - so you can enforce a validity period and also purge old tokens

The logic around it will be straightforward. You don't need django-sesame.
