### ISSUE TITLE
Add support for BigAutoField

### ISSUE THREAD

**Issue by hannseman** [aaugustin/django-sesame#48]
It would be nice to have support for [BigAutoField](https://docs.djangoproject.com/en/3.0/ref/models/fields/#bigautofield) primary keys. 

Would it be possible to just use the `IntPacker` for this field or do we have to introduce a `LongPacker`:
```python
class LongPacker(object):
    @staticmethod
    def pack_pk(user_pk):
        return struct.pack(str("!l"), user_pk)

    @staticmethod
    def unpack_pk(data):
        return struct.unpack(str("!l"), data[:4])[0], data[4:]
```

**Comment by aaugustin** [comment]
You need 8 bytes for 64-bits integers in `BigAutoField`. This requires a new packer.

**Comment by aaugustin** [comment]
Oooooops — I was working on a pull request on my end and didn't notice yours, which was perfectly correct, until I pushed my changes. Sorry :'(

**Comment by aaugustin** [comment]
It doesn't seem useful to run all tests in `test_backends.py` with all possible primary key types, but it may be interesting to run the most common ones: AutoField, BigAutoField, UUIDField. So I'm going to grab these changes from your PR.

**Comment by hannseman** [comment]
> Oooooops — I was working on a patch on my end and didn't notice your pull request, which was perfectly correct, until I pushed my changes. Sorry :'(

No problem! I should've been clear about that I intended to create a PR. Thanks for the quick fix! 👍

**Comment by aaugustin** [comment]
FYI version 1.8 is released on PyPI with this feature.
