### ISSUE TITLE
Debugging invalid Tokens

### ISSUE THREAD

**Issue by migueltorrescosta** [aaugustin/django-sesame#50]
When a user tries to authenticate his session with an invalid token, is there any way to understand why? I was thinking of along the lines of seeing if the cause is that the token has already been used (I have one-time-use tokens set to True), or if the token has expired, or being able to get some clue as to why it has failed.

I am not interested in doing this to show to the users, I am interested in it for debugging purposes.

Best,
Miguel

**Comment by aaugustin** [comment]
Enabling the `sesame.backends` logger at the debug level should provide this information:
https://github.com/aaugustin/django-sesame/blob/5056e8175e42bb963e86a54d80fd21cc7cb86731/sesame/backends.py#L120-L154

**Comment by aaugustin** [comment]
If this works for you, could you close the issue?

**Comment by aaugustin** [comment]
Tentatively closing.

**Comment by migueltorrescosta** [comment]
I am sorry for my inactivity, I stayed away from GitHub for a while and forgot about this. Thank you for your help @aaugustin !
