### ISSUE TITLE
Django-sesame use case : login with mail + magic link

### ISSUE THREAD

**Issue by petijean** [aaugustin/django-sesame#58]
Hello,
Would anyone have implemented django-sesame in a django project to enable the solution "login by mail" ?
- Users without 'username' or 'password'
- Users would only provide an email adress used to sent them a 'magic link' (whose validity would be time-limited) to sign in or log in

**Comment by aaugustin** [comment]
I told @petijean to post here as I'm not aware of any off-the-shelf solution for this. Apparently no one else does. A search didn't turn up anything.

Solving this requires several parts, but they're all quite straightforward and well documented:

- make a customer user model that uses the email as username
- render a form with an email address fields
- when the form is submitted successfully, generate a link with a token and send an email to the user with that link

The default configuration of django-sesame does the rest.

**Comment by aaugustin** [comment]
Version 3.0 will contain a tutorial with detailed steps to achieve this.

**Comment by fabge** [comment]
but how would you achieve this if you want to create the user *after* he has clicked the link. not before sending the mail? because `sesame.utils.get_query_string` expects a user as parameter.

**Comment by aaugustin** [comment]
Answered [there](https://github.com/aaugustin/django-sesame/issues/47#issuecomment-2323466531).
