### ISSUE TITLE
Using IP in signature

### ISSUE THREAD

**Issue by manelclos** [aaugustin/django-sesame#62]
Hi,

We are using django-sesame and sending the OTP over email, so we hit the problem with `SESAME_ONE_TIME=True` and the email server checking the links. As per the documentation we will change to `SESAME_ONE_TIME=False`, and a short `MAX_AGE`.

Would it be possible to have a configuration option to include the user's `IP` in the signature? `authenticate` could pass the `request` or the `IP` to `parse_token`, and in the same way we would be passing the `request` or `IP` to `create_token`.

This, along with a well configured webserver/proxy, would allow us to use `SESAME_ONE_TIME=True` again, plus a bigger `MAX_AGE` which is IMHO better for users.

Thanks in advance!

**Comment by aaugustin** [comment]
If you're verifying tokens with get_user (as opposed to using the middleware) maybe you can achieve this by using the user's IP address as a token scope. I'm interested in hearing if that works.

**Comment by aaugustin** [comment]
Flagging as a doc issue because that would be interesting to explain if it works.

**Comment by aaugustin** [comment]
I can think of several scenarios where the user would open a link from a device that doesn't have the same IP address than the device from which they requested it, which I why I was "interested in hearing if that works".

Considering this uncertainty and the absence of feedback after two months, I'm going to close the issue.
