### ISSUE TITLE
Crash with malformed base64 sesame tokens

### ISSUE THREAD

**Issue by tasn** [aaugustin/django-sesame#64]
When sesame is passed malformed tokens the middleware just throws an exception. This can happen, for example, when the user copies the URL incorrectly or if the URL isn't processed correctly by some user app (such as #63).

For example, if you try this:
http://localhost/dashboard/?sesame=oeuh3

You'll get `Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4` as the error.

Expected behaviour: treat it as a bad token rather than crashing.

**Comment by aaugustin** [comment]
Fixed!

**Comment by tasn** [comment]
Thanks!
