### ISSUE TITLE
Backporting for django 1.x and python 2.x

### ISSUE THREAD

**Issue by hovi** [aaugustin/django-sesame#66]
Hi,

I am trying to use sesame current latest 1.x django (`1.11.27`). Sadly I still have to use python 2.x for this project.

Seems like latest version supporting python 2.x is `1.7`. It however isn't compatible with latest 1.x django due to `get_response` parameter of middleware constructor not having default `None` value:
https://docs.djangoproject.com/en/1.11/topics/http/middleware/#init-get-response

I suggest adding to documentation, that 1.7 is latest and backport this so that it's working with latest 1.x django. I don't mind making pull request if you are willing to take time checking and merging it. I am fine either way, can install from custom branch.
Thank you for the project!

**Comment by aaugustin** [comment]
I'm sorry to hear you're stuck with Python 2 past its end-of-life.

Caring about Python 2 isn't a good use of my time at this point.

**Comment by aaugustin** [comment]
I'm wondering if you're confusing with another project because websockets never supported Python 2.

https://websockets.readthedocs.io/en/stable/faq.html#is-there-a-python-2-version
