### ISSUE TITLE
get_parameters not working in Django 3.2

### ISSUE THREAD

**Issue by thomascenni** [aaugustin/django-sesame#69]
I am migrating an existing project from Django 3.1.8 to Django 3.2.
Sesame stopped working, the error is in tokens_v2.py, line 129, in create_token

primary_key = packers.packer.pack_pk(user.pk)

I think it might be related to this change, which affect also user model:

https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

Is it possible to add Django 3.2 to the tests?

**Comment by aaugustin** [comment]
Tests pass on Django 3.2 (see 32fdc0e).

Could you please provide :

1. the complete stack trace of the exception
2. the value of the `DEFAULT_AUTO_FIELD` and `SESAME_PACKER` settings (if they're defined)
3. the output of `from django.contrib.auth import get_user_model; get_user_model()._meta.pk.get_internal_type()`

**Comment by thomascenni** [comment]
Hello,

1. Complete stack
```
Traceback (most recent call last):
  File "/projects/p1/.env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/projects/p1/.env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/projects/p1/app/views.py", line 100, in SetupUserView
    profile_url = generate_token_url(request, user, scope, serial_id)
  File "/projects/p1/app/utils.py", line 23, in generate_token_url
    token_url += get_query_string(user, scope=scope)
  File "/projects/p1/.env/lib/python3.8/site-packages/sesame/utils.py", line 25, in get_query_string
    return "?" + urlencode(get_parameters(user, scope))
  File "/projects/p1/.env/lib/python3.8/site-packages/sesame/utils.py", line 17, in get_parameters
    return {settings.TOKEN_NAME: get_token(user, scope)}
  File "/projects/p1/.env/lib/python3.8/site-packages/sesame/tokens.py", line 16, in create_token
    return tokens.create_token(user, scope)
  File "/projects/p1/.env/lib/python3.8/site-packages/sesame/tokens_v2.py", line 129, in create_token
    primary_key = packers.packer.pack_pk(user.pk)
  File "/projects/p1/.env/lib/python3.8/site-packages/sesame/packers.py", line 59, in pack_pk
    return struct.pack(cls.fmt, user_pk)
struct.error: required argument is not an integer
```
2. DEFAULT_AUTO_FIELD = 'hashid_field.BigHashidAutoField' from https://github.com/nshafer/django-hashid-field (django-hashid-field==3.2.1)
    SESAME_PACKER not defined
4. The output is 'BigAutoField'

Going back to Django 3.1.8, everything works correctly (the development started in an earlier version, I really got the problem when upgrading to Django 3.2).

**Comment by thomascenni** [comment]
Hello,
Just found the error, I need to define the
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
djang-sesame where not able to get user_pk because it was getting a Hashid object.

**Comment by aaugustin** [comment]
Maybe django-hashid-field has a different behavior on Django 3.2?

Anyway, the problem is that django-hashid-field's BigHashidAutoField pretends that it's native BigAutoField: https://github.com/nshafer/django-hashid-field/blob/cc0287119b1093015816954bf3e5dca21a44b8ec/hashid_field/field.py#L184-L185

But it's quite different: unlike `BigAutoField` its value cannot be used as an `int`, which trips django-sesame.

Forcing `BigAutoField` solves the problem but you may be losing behaviors that you expect from django-hashid-field.

If you want to use `BigHashidAutoField`, you can set `SESAME_PACKER` to something appropriate for the underlying type, maybe `sesame.packers.StrPacker`.

**Comment by thomascenni** [comment]
Thanks for the hints.
Actually my user model is a custom one (it extends AbstractUser), but it doesn't have a hashid-field.
The BigHashidAutoField is used in another model, but I suppose django-sesame was using the DEFAULT_AUTO_FIELD setting.
