### ISSUE TITLE
Webmail Links Not Working

### ISSUE THREAD

**Issue by kfranznick** [aaugustin/django-sesame#71]
I'm seeing an issue where linked viewed in webmail clients are being truncated when clicked on - resulting in a login failure. This seems to be a recent change to webmail or browsers as it didn't happen last year. Copy/paste of the same link from the webmail message to the address bar work fine. I'd welcome any suggestions for working round this issue.

**Comment by aaugustin** [comment]
django-sesame is already heavily optimized to generate relatively short links.

You can set SESAME_TOKEN_NAME to a one-character string to save a few bytes.

You could save a few more bytes by reducing SESAME_SIGNATURE_SIZE; however, every byte you remove saves little URL size and removes a lot of security; so I would advise against that.

Probably you should look at this problem from the perspective of:

- the length of the rest the URL;
- how you insert URLs in emails — which has very little to do with django-sesame.
