### ISSUE TITLE
Django admin does not log in after adding Middleware

### ISSUE THREAD

**Issue by rokdd** [aaugustin/django-sesame#76]
I want to achieve to log in by django-sesame and django-admin by password. The login is working with password until I add the `sesame.middleware.AuthenticationMiddleware` into settings. Django just says that I have the wrong password, so there is no error. My user model looks like this:

```
class User(AbstractUser):
	objects = UserManager()
	def __int__(self):
		return self.id
	class Meta:
		db_table='auth_user'
		pass
```

I could not find any ticket or issue regarding the django-admin. Do I have not seen something in the settings or what I am doing wrong?

**Comment by adamchainz** [comment]
If you'd like to consider contributing a django system check to check for this, I'd be open to reviewing it.

**Comment by rokdd** [comment]
Well I mean some ppl might be not like to use the Django Backend, so then in the check it would like mandatory? Or do I understand this wrong?

**Comment by rokdd** [comment]
Sure. But the Django backend, which I was missing in my settings, is only required when you use the native login of Django somewhere.

**Comment by adamchainz** [comment]
Oh right, it wasn't clear from your comment that it was the Django backend you were missing, rather than sesame's.

**Comment by aaugustin** [comment]
If that's clearer, then we could similarly do:

```python
MIDDLEWARE += [
    ...,
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "sesame.middleware.AuthenticationMiddleware",  # add this line
    ...,
]
```

which is easier to visualize than:

> The best position for `sesame.middleware.AuthenticationMiddleware` is just after `django.contrib.auth.middleware.AuthenticationMiddleware`.

**Comment by rokdd** [comment]
Well my problem was the backend... so I would say the snippet should change like this:

**Comment by adamchainz** [comment]
#77 does that :)
