### ISSUE TITLE
DRF support

### ISSUE THREAD

**Issue by bellum** [aaugustin/django-sesame#8]
I appreciate your work @aaugustin. Wanted to discuss with you one thing.

This package can be useful for rest-framework too. For my purposes I have taken `sesame.backends.UrlAuthBackendMixin` and mixed it with `rest_framework.authentication.BaseAuthentication`.
This is what I had to change:
- take token from request in `Authentication` rather than in `Middleware`
- raise `rest_framework.exceptions.AuthenticationFailed` in case token is wrong
- add `get_user` and `user_can_authenticate` methods from `django.contrib.auth.backends.ModelBackend`

But I would propose to support DRF natively. I can prepare PR but maybe you have some vision of how this should be implemented in the best way? 

Thank you.

**Comment by aaugustin** [comment]
I think that's a good solution. I made `sesame.backends.UrlAuthBackendMixin` separate from `sesame.backends.ModelBackend` to allow this approach.

Since I can't see your code, it's hard to comment about the changes you list.

> take token from request in `Authentication` rather than in `Middleware`

If I understand correctly you moved the logic to a custom DRF authentication backend called by the standard DRF auth system and you didn't use sesame's middleware. I haven't customized DRF auth recently, I don't know how it works exactly, but this seems reasonable.

> raise `rest_framework.exceptions.AuthenticationFailed` in case token is wrong

Yes, that's all right.

> add `get_user` and `user_can_authenticate` methods from `django.contrib.auth.backends.ModelBackend`

Yes, it's up to you to implement `get_user` in a custom auth backend. `django-sesame` only gives you an id.

I'm not sure about `user_can_authenticate`. It isn't part of the API for custom user models or custom auth backends. Perhaps DRF needs it.

When you talk of supporting DRF natively, are you talking of adding a DRF backend to django-sesame?

We can do that as follows:

- turn the `backends` module into a package
- put a `rest_framework` module in this package
- make sure DRF isn't a dependency of django-sesame (except for running tests)

**Comment by bellum** [comment]
Sorry for not posting the code.

I have not thought about impossibility to use rest_framework.authentication.BaseAuthentication inside django-sesame.

```python
class DRFSesameAuthentication(UrlAuthBackendMixin, BaseAuthentication):
    """
    1. Supports django-rest-framework custom authentication protocol defined here:
    http://www.django-rest-framework.org/api-guide/authentication/#custom-authentication

    2. Gets token as it's done in sesame.middleware.AuthenticationMiddleware
    """

    def parse_token(self, token):
        """
        REWRITTEN to raise rest_framework.exceptions.AuthenticationFailed on errors

        Obtain a user from a signed token.

        """
        try:
            data = self.unsign(token)
        except signing.SignatureExpired:
            # changed: exception instead of log
            raise exceptions.AuthenticationFailed("Expired token")
        except signing.BadSignature:
            # changed: exception instead of log
            raise exceptions.AuthenticationFailed("Bad token")
        user = self.get_user(*struct.unpack(str('!i'), data[:4]))
        if user is None:
            # changed: exception instead of log
            raise exceptions.AuthenticationFailed("Unknown token")
        h = crypto.pbkdf2(
            user.password, self.salt, self.iterations, digest=self.digest)
        if not crypto.constant_time_compare(data[4:], h):
            # changed: exception instead of log
            raise exceptions.AuthenticationFailed("Invalid token")
        return user

    def authenticate(self, request):
        token = request.GET.get(TOKEN_NAME)
        if token is None:
            return None

        user = self.parse_token(token)
        return user, token

    # copied as is from django.contrib.auth.backends.ModelBackend
    def get_user(self, user_id): pass

    # copied as is from django.contrib.auth.backends.ModelBackend
    def user_can_authenticate(self, user): pass
```

Not to create new package I see alternative to adjust `UrlAuthBackendMixin` with new method to handle token errors (let it be `broken_error_handler`) and to create new mixin separately for DRF which gonna:
- raise exceptions in `broken_error_handler` instead of logging or as extra logic
- get token from request.GET and return (user, token) in its `authenticate` method
- likely repeat get_user and user_can_authenticate methods

If you agree with I gonna prepare PR and cover changes with tests.

**Comment by aaugustin** [comment]
Sorry, I just noticed I failed to follow up on this discussion.

I'm willing to accept modifications to support DRF if they aren't too invasive.

I'm not a big fan of explaining /why/ the token didn't work. Anyway all the user can do is double-check they provided the correct token and, failing that, generate a new one. You could convert "`parse_token` returns `None`" to "`raise exceptions.AuthenticationFailed()`" without modifying the current implementation.

**Comment by aaugustin** [comment]
Since there isn't any momentum on this issue and since I expect most DRF users to go with the built-in [token authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication), I'm going to close this issues.

**Comment by schwartzie** [comment]
I know this is a long-dead thread but I came across it when plugging sesame 3.1 into DRF 3.14 and just wanted to share what worked for me with a project using a `ModelBackend` for anyone else who might find themselves here:

```py
from sesame.backends import ModelBackend
from sesame.tokens import parse_token
from sesame.settings import TOKEN_NAME
from rest_framework.authentication import BaseAuthentication


class SesameAuthentication(ModelBackend, BaseAuthentication):

    def authenticate(self, request):
        token = request.data.get(TOKEN_NAME)

        if token is None:
            return None

        user = parse_token(token, self.get_user)
        return user, token
```
