### ISSUE TITLE
Expired Token: enhance user journey

### ISSUE THREAD

**Issue by patroqueeet** [aaugustin/django-sesame#88]
me again once more :)

after using sesame now for a long time for thousands of users, we see that many of them are running into expired links from emails, which are lying around for days when the expiration is 24hrs only. when the user clicks such an expired link, what would you consider to be a good and secure user journey with final goal of granting access to a valid user? would that make a good enhancement to this lib?

**Comment by aaugustin** [comment]
I think it is highly dependent on your use case. django-sesame takes care of generating and validating authentication tokens, with well defined security properties but it doesn't provide any user flows and I don't see a good way to provide such flows.

You can call `get_user(token, max_age=<very large value>)` to override the expiration, get the user, and resend them a token — if that flow fits your use case.

**Comment by patroqueeet** [comment]
hey, fine for me. having that already in place :)
