### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by dannwise** [aaugustin/django-sesame#93]
Do you have any plan to update deprecated dependencies such as pycrypto and keyczar?

**Comment by aaugustin** [comment]
I am confused about your report given that django-sesame:

* only depends on django and (optionally) on ua-parser
* only requires a minimal version i.e. doesn't prevent you to update

To answer your question literally, no, I have no plans to do anything related to dependencies.

**Comment by dannwise** [comment]
Hey @aaugustin thank your for your reply. 

I had django-sesame installed on a virtualenv and after formatting my pc, when trying to reinstall it with pip I was having all sorts of issues with the mentioned dependencies. Even checked the new dist-info and they were there. Luckly I had a backup of the virtualenv and after rechecking the old dist-info of django-sesame I see that I was probably doing something wrong with the new installation. Maybe I forgot the "django" part and was trying to install a similarly named package. Anyways, thank you once more for your reply and I'm sorry for the confusion.
