### ISSUE TITLE
minimum ua parser version

### ISSUE THREAD

**Issue by caleb15** [aaugustin/django-sesame#94]
The min version of ua-parser required by sesame currently has a security issue: https://security.snyk.io/vuln/SNYK-PYTHON-UAPARSER-1298047

To avoid the possibility of a user of django-sesame getting DOS'd I would suggest pinning the minimum version to 0.15.0

**Comment by aaugustin** [comment]
Thank you!

**Comment by caleb15** [comment]
No, thank you! :)
