### ISSUE TITLE
override_settings doesn't update sesame settings

### ISSUE THREAD

**Issue by johnnymetz** [aaugustin/django-sesame#98]
**Steps to Reproduce**

I'm using django-environ to manage my settings. Let's say I have something like this to manage `SESAME_ONE_TIME`:

```
import environ

env = environ.Env(
    SESAME_ONE_TIME=(bool, False),
)

SESAME_ONE_TIME = env("SESAME_ONE_TIME")
```

I want to write a test to ensure setting `SESAME_ONE_TIME=True` works as expected:

```
from http import HTTPStatus

from django.conf import settings
from django.contrib.auth.models import User
from django.test import TestCase, override_settings
from django.urls import reverse
from sesame import settings as sesame_settings
from sesame.settings import load as load_sesame_settings
from sesame.utils import get_query_string

class TestMagicLinks(TestCase):
    @staticmethod
    def _build_magic_link(user):
        return reverse("sesame-login") + get_query_string(user)

    @override_settings(SESAME_ONE_TIME=True)
    def test_one_time_link(self):
        user = User.objects.create_user(username="test", password="test")
        magic_link = self._build_magic_link(user)

        # First time we use the magic link, it should work
        response = self.client.get(magic_link)
        assert response.status_code == HTTPStatus.NO_CONTENT.value

        # Second time we use the magic link, it should fail
        response = self.client.get(magic_link)
        assert response.status_code == HTTPStatus.FORBIDDEN.value  # Fails here because response.status_code = 204
```

The `test_one_time_link` test is failing because the second status code assertion returns 204, instead of the expected 403.

The test passes if I do either of the following things:

- Set the default `SESAME_ONE_TIME` setting to True. For example:

```
env = environ.Env(
    SESAME_ONE_TIME=(bool, True),
)
```

- Run `sesame.settings.load()` at the beginning of the test. For example:

```
class TestMagicLinks(TestCase):
    @override_settings(SESAME_ONE_TIME=True)
    def test_one_time_link(self):
        sesame.settings.load()
        # rest of the test
```

**Hypothesis**

Looks like `override_settings()` isn't updating the sesame settings. I think the following failing test proves this:

```
from django.config import settings as django_settings
from sesame import settings as sesame_settings

class TestMagicLinks(TestCase):
    @override_settings(SESAME_ONE_TIME=True)
    def test_settings(self):
        assert django_settings.SESAME_ONE_TIME is True
        assert sesame_settings.ONE_TIME is True  # Fails here because sesame_settings.ONE_TIME is False
```

**Comment by aaugustin** [comment]
If you want to override django-sesame settings, you need this: https://github.com/aaugustin/django-sesame/blob/main/tests/signals.py

**Comment by aaugustin** [comment]
I'm leaving this issue open because we could discuss moving that function to the sesame package itself and making it a public API. Since you're the first person to ask in more than a decade, the use case seems... uncommon.

**Comment by adamchainz** [comment]
I think moving it into the main package would be good practice. Django puts some of its `setting_changed` receivers in the main package, for example: https://github.com/django/django/blob/2360ba22742c3ee8729697bfe2d508110465af56/django/contrib/auth/hashers.py#L130-L134 . Many live within `django.test` too, but ofc that's guaranteed to be loaded during tests, whilst any `sesame.test` module won't be.

**Comment by aaugustin** [comment]
> whilst any `sesame.test` module won't be.

... all the more since the `tests` package lives outside of the `sesame` package and isn't part of releases!

**Comment by aaugustin** [comment]
Is #100 what you had in mind?

**Comment by aaugustin** [comment]
Version 3.2, which includes this feature, is available on PyPI.
